on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        npm install
        
        git clone https://eaas.dev/eaas-local-installer
        cd eaas-local-installer
        sudo apt remove -y moby-containerd moby-runc
        sudo scripts/install-test-server.sh
        
        while ! curl http://localhost:8080/emil/; do sleep 1; done
